In [43]:
import numpy as np
import matplotlib as plt
import itertools as it

J = -1

In [44]:
class lattice:
    def __init__(self, ndims, length): # If want non-square lattice, make length an array/tuple
        self.ndims = ndims
        self.length = length
        # np.full creates an array of length ndims with values of length, to create the size tuple
        # Change to size=length for non-square lattice
        self.points = np.random.choice(a=[-1, 1], size=tuple(np.full(ndims, length, dtype=int)))
        self.erg = 0
        self.mag = np.sum(self.points) / self.length**self.ndims # Change to product along entries of length for non-square lattice

    def update_E(self):
        energy = 0
        # itertools.product creates the adjacent and diagonal neighbors of any ndarray point
        for index in it.product(range(-1,self.length-1), repeat=self.ndims):
            neighbors = []
            for rel_pos in it.product((-1, 0, 1), repeat=self.ndims): # Loop over all neighbors
                # Exclude the point itself and all diagonal neighbors
                if not all(i == 0 for i in rel_pos) and not all(i != 0 for i in rel_pos): 
                    neighbors.append(self.points[tuple(i + i_rel for i, i_rel in zip(index, rel_pos))]) # Add neighbor spin values
            neighbors = np.array(neighbors)
            energy += J * np.sum(neighbors * self.points[index]) # Add to energy
        self.erg = energy / 2 # divide by 2 for double-counting
    def update_M(self):
        self.mag = np.sum(self.points) / self.length**self.ndims

In [45]:
L1 = lattice(2,4)
print(L1.points)
L1.update_E()
print(L1.erg)
print(L1.mag)

[[ 1  1  1  1]
 [-1 -1 -1  1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]]
0.0
0.125
